### ISSUE TITLE
Token获取问题

### ISSUE THREAD

**Issue by ravenxrz** [rxliuli/joplin-search-intergration#1]
谢谢你的工作，想问一下如何获取joplin的token？
最好能在readme中添加下说明。

**Comment by rxliuli** [comment]
目前功能上还未完善，可能稍后会补充文档，可以参考：https://joplinapp.org/clipper/

![image](https://user-images.githubusercontent.com/24560368/110467299-cdac9980-8111-11eb-8b1d-025ac449bcea.png)

**Comment by rxliuli** [comment]
文档已更新：https://github.com/rxliuli/joplin-search-intergration/blob/master/README.ZH_CN.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
