### ISSUE TITLE
笔记显示建议

### ISSUE THREAD

**Issue by ravenxrz** [rxliuli/joplin-search-intergration#3]
初步体验，搜索效果还是很不错的。但是搜索后点击进去的显示效果不太好。
比如边距几乎没有，latex数学公式无法渲染，代码显示有问题（不知道是不是我有什么插件冲突了）。
![image-20210317140052265](https://cdn.jsdelivr.net/gh/ravenxrz/PicBed/img/image-20210317140052265.png)

如果能直接跳转到joplin对应页面是最好的，或者能否唤起系统内的第三方md编辑器（比如typora)。

**Comment by rxliuli** [comment]
> 初步体验，搜索效果还是很不错的。但是搜索后点击进去的显示效果不太好。
> 比如边距几乎没有，latex 数学公式无法渲染，代码显示有问题（不知道是不是我有什么插件冲突了）。

**Comment by rxliuli** [comment]
> 初步体验，搜索效果还是很不错的。但是搜索后点击进去的显示效果不太好。

请在 [release](https://github.com/rxliuli/joplin-search-intergration/releases) 下载 v0.1.3 解压后安装，实际效果如下

![image](https://user-images.githubusercontent.com/24560368/111422813-428f5d00-872a-11eb-8add-aab06fbe3201.png)

Chrome 商店版本正在审核中。。。

![image](https://user-images.githubusercontent.com/24560368/111422886-5cc93b00-872a-11eb-932b-55328eb913ff.png)

> 比如边距几乎没有，latex 数学公式无法渲染，代码显示有问题（不知道是不是我有什么插件冲突了）。

latex 数学公式目前尚未添加插件支持，后续我看下怎么支持吧（这周末）

> 如果能直接跳转到 joplin 对应页面是最好的

这点目前做不到，joplin 不提供自定义协议

> 或者能否唤起系统内的第三方 md 编辑器（比如 typora)。

只能通过 joplin api 打开 joplin 中指定的外部编辑器

**Comment by ravenxrz** [comment]
升级到0.1.3显示效果依然如此，chrome和edge（edge禁用了其他所有插件）：








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rxliuli/joplin-search-intergration] 笔记显示建议 (#3)





  
初步体验，搜索效果还是很不错的。但是搜索后点击进去的显示效果不太好。
  
请在 release 下载 v0.1.3 解压后安装，实际效果如下
 

 
Chrome 商店版本正在审核中。。。
 

  
比如边距几乎没有，latex 数学公式无法渲染，代码显示有问题（不知道是不是我有什么插件冲突了）。
  
latex 数学公式目前尚未添加插件支持，后续我看下怎么支持吧（这周末）
  
如果能直接跳转到 joplin 对应页面是最好的
  
这点目前做不到，joplin 不提供自定义协议
  
或者能否唤起系统内的第三方 md 编辑器（比如 typora)。
  
只能通过 joplin api 打开 joplin 中指定的外部编辑器

**Comment by rxliuli** [comment]
> 升级到 0.1.3 显示效果依然如此，chrome 和 edge（edge 禁用了其他所有插件）：
> […](#)
> ------------------&nbsp; 原始邮件 & nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021 年 3 月 17 日 (星期三) 下午 2:11 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [rxliuli/joplin-search-intergration] 笔记显示建议 (#3) 初步体验，搜索效果还是很不错的。但是搜索后点击进去的显示效果不太好。 请在 release 下载 v0.1.3 解压后安装，实际效果如下 Chrome 商店版本正在审核中。。。 比如边距几乎没有，latex 数学公式无法渲染，代码显示有问题（不知道是不是我有什么插件冲突了）。 latex 数学公式目前尚未添加插件支持，后续我看下怎么支持吧（这周末） 如果能直接跳转到 joplin 对应页面是最好的 这点目前做不到，joplin 不提供自定义协议 或者能否唤起系统内的第三方 md 编辑器（比如 typora)。 只能通过 joplin api 打开 joplin 中指定的外部编辑器 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

稍等，吾辈已经知道是哪里的问题了，稍后我会发布一个 v0.1.4 的版本（目前需要设置系统的暗色模式）

**Comment by rxliuli** [comment]
已发布 v0.1.4
https://github.com/rxliuli/joplin-search-intergration/releases/tag/v0.1.4

在本地编辑器中打开和 latex 可能要稍晚一点了，参考：https://github.com/rxliuli/joplin-search-intergration/issues/4
